### ISSUE TITLE
Criar nova pasta Migrations dentro de DAO para executar criação e drop de tabelas

### ISSUE THREAD

**Issue by igotfr** [scoorpionx/POO-II#5]
a tabela Cliente está sendo criada dentro da class DB, no método createTables().
A criação e drop de tabelas deve ser feita e executada separadamente (não sei como executar separadamente no Visual Studio) em Migrations

**Comment by scoorpionx** [comment]
Esse problema será levantado futuramente, caso a aplicação cresça mais.

**Comment by igotfr** [comment]
> Esse problema será levantado futuramente, caso a aplicação cresça mais.

mano, deixa aberto, mesmo qe seja pra 2050

**Comment by scoorpionx** [comment]
Os issues ficam registrados no repositório e são fechados por inatividade automaticamente (só estou adiantando pro repo ficar atualizado), mas podem ser reabertos a qualquer momento.
